import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={inter.className + ' bg-gradient-to-br md:bg-gradient-to-r from-primary to-purple-800 md:from-purple-800 md:via-primary md:to-secondary text-text'}>
                {children}
            </body>
        </html>
    );
}
